webform.webform.*.third_party.webform_score:
  type: sequence
  label: 'Scorable Fields'
  sequence:
    field_name:
      type: string
    score_amount:
      type: integer
    score_validation_method:
      type: string
    score_validation_data:
      type: string
